name: Playwright Tests

on:
  pull_request:
    branches: [ develop, staging, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: コードをチェックアウト
      uses: actions/checkout@v4

    - name: Node.jsをセットアップ
      uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Cache Node.js modules
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: 依存関係をインストール
      run: npm ci

    - name: Cache Playwright browsers
      uses: actions/cache@v3
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-playwright-

    - name: Playwrightブラウザをインストール
      run: npx playwright install --with-deps

    - name: Playwrightテストを実行
      run: npx playwright test --reporter=html